### PR TITLE
Avl again

### PR DESCRIPTION
**Pull request by rowanwins**
So I wasn't able to commit to your `rowanwins-use-avl` branch so I've had to create another, sorry about that. 

But the good news is I've added a couple of lines and `union` now appears to work, tests are passing and both demo pages are working....

### CODE REVIEW

**Comment by w8r** [comment]
You are amazing! I will check out as soon as I get out of plane and I could start looking at proper benchmarks 

Kind regards,
Alexander Milevski

**Comment by rowanwins** [comment]
Am also adding in `benchmark.js` for run performance tests, we can run these for incremental  updates to check performance doesnt degrade, and it'll also allow us to test against `jsts`

**Comment by rowanwins** [comment]
So looking at the benchmarks `martinez` smashes `jsts` on the small geometries however on the larger geometries (eg the asia.geojson) then suddenly things even out...

**Comment by w8r** [comment]
I will dig. The same operation (asia vs square) run in the browser is up to 10x faster with intersection.

**Comment by w8r** [comment]
So far I found out the bottleneck in a rather tricky spot of combining the rings where there are multiple nested `while`s. Also I have split the code into more files to be able to navigate better. Again, it's in a branch made out of your PR, but I will grant you access to the repo to eliminate these problems for you

**Comment by rowanwins** [comment]
Awesome, thanks @w8r . Yeah I had my suspicion about those `while` loops in my preliminary investigations... Let me know where you get to and if you get stuck.

**Comment by w8r** [comment]
according to the benchmarks it eats a hell of a lot of time (like 30%) to iterate on those result arrays because of that. As far as I can remember, the paper doesn't cover it at all and it is a weird trick in the code, which was even meant to be an optimization.

**Comment by w8r** [comment]
I will kill this one to keep it clear, the work has been transferred into #42

**Pull request closed without merging**
