### PR TITLE
First attempt at replacing rbtree

### PR DESCRIPTION
**Pull request by rowanwins**
Gday @w8r 

I've had a first attempt at replacing the rbtree with the [functional-rb-tree package](https://github.com/mikolalysenko/functional-red-black-tree).

There is currently one test not passing. Using the demo/index.html everything appears to pass visually, although if I look at the asia example then I start getting all the bugs (particuarly "Edges of the same polygon overlap")

Obviously it needs additional work but I thought I'd send this through anyway just in case it helps with the investigations. I'll take another look tomorrow but I thought I'd send this through in case in helps in any way or if you could provide additional guidance.

Cheers
Rowan

PS Great work so far - this is a mind-bending problem so you've done exceptionally well to get this far, I'm trying my best to follow along :)

### CODE REVIEW

**Comment by w8r** [comment]
Thank you so much for your help! this rb-tree implementation by @mikolalysenko is brilliant but I seriously doubt it is fast. But at this point it doesn't matter, I've implemented a [couple of binary trees myself](https://github.com/w8r/binary-trees) hoping to use it for this project. I will try out your code and try to move forward with it.

Did you manage to get rid of that problem when the events could not be retrieved after being put into the tree?

Thank you again for your interest and effort.

**Comment by rowanwins** [comment]
Hi @w8r 

Based on the demo page using the horseshoe.json the performance is a little slower than the existing rbtree library that you're using. So for example
````
Intersection with bintrees = 5.260ms
Intersection with functional-rb-tree = 5.634ms
Union with bintrees = 958ms
Union with functional-rb-tree = 985ms
````
The sweep events appear to readily retrievable using the functional-rb-tree although Im still grappling with how all the code works so don't take my word for it :)

I'll try and find a bit more time for it today and let you know if I make any more progress.

**Comment by w8r** [comment]
Thanks a lot! You just proved the point I was stating to the other contributor: since that tree never holds more than 10-20 events at once, its implementation is not so critical ))
To check if the bug pops up or not you can get rid of this ugly piece of code https://github.com/w8r/martinez/blob/master/src/index.js#L341 

Thumbs up for digging into that iterator madness there

**Comment by rowanwins** [comment]
So at the moment when working with the asia.json intersection and xor appear to be working. Intersection goes very quickly compared to jsts but xor is only marginally quicker
````
XOR martinez: 452.694ms
XOR jsts: 485.342ms

Intersect martinez: 31.669ms
Intersect jsts: 235.806ms
````
Union and difference are still both producing errors.

I don't appear to be hitting the brute code at all.

**Comment by rowanwins** [comment]
Also FYI just out of interest I ran the asia.json through a geometry check in QGIS and it returns 90 errors, below is a sample, all the other errors are pretty much the same

````
0,segment 0 of ring 4 of polygon 253 intersects segment 0 of ring 0 of polygon 268 at 117.907039028, 4.15668301495
0,segment 0 of ring 0 of polygon 255 intersects segment 0 of ring 482 of polygon 278 at 116.590226685, 4.331132101
0,segment 0 of ring 10 of polygon 255 intersects segment 0 of ring 472 of polygon 278 at 116.924263143, 4.344955547
0,segment 0 of ring 25 of polygon 255 intersects segment 0 of ring 457 of polygon 278 at 117.498388306, 4.172614644
0,segment 0 of ring 1424 of polygon 255 intersects segment 0 of ring 894 of polygon 278 at 109.645274285, 2.083238023
0,segment 0 of ring 1425 of polygon 255 intersects segment 0 of ring 893 of polygon 278 at 109.626620728, 2.02969635
0,segment 0 of ring 1430 of polygon 255 intersects segment 0 of ring 888 of polygon 278 at 109.529365682, 1.905156149
````
I just repaired the geometry errors using ArcMap and reran the geometry check in QGIS and now I dont get any errors. Now running the the martinez algorithm works fine! I'll commit the new asia.json file so you can have a look.

**Comment by w8r** [comment]
@rowanwins amazing work! I suspected that the `asia` file is broken, though I created it with GDAL. Did you see the more trivial testcases in other issues?

**Comment by w8r** [comment]
screenshot 2017-02-14 07 36 15
nice!

**Comment by rowanwins** [comment]
Hi @w8r 

I've had a look at some of the other test cases but they still appear to be failing. I'm not sure what the goal is in terms of supporting weird polygon variations in terms of validity.

Things also appear to be going quite slow with depending on circumstances so I'm not sure if we can optimise the use of the entree (I'm sure we can, just need to work out how!).

Anyway hope this provides a few useful leads for you, I'm still grappling with how it all works so it feels like stabs in the dark at times!

**Comment by w8r** [comment]
I took most of your changes, can't thank you enough

**Comment by rowanwins** [comment]
No worries @w8r , glad to have a played a small part in helping out.

I just pulled down the latest and it appears to be working great although performance looks to be a bit slower than JSTS so Im not sure if there are any additional optimisations that can be made, it'll probably be a little while before I can sit down and do some proper performance testing.

Anyway great progress none the less!

**Pull request closed without merging**
