### PR TITLE
Use avl tree

### PR DESCRIPTION
**Pull request by rowanwins**
Hey @w8r 

So I've started looking at this again, attached is my first pass replacement which doesnt appear to be working... To be honest I've got no idea where exactly Im failing, understanding these fancy pants tree structures is all new to me :)

### CODE REVIEW

**Comment by w8r** [comment]
Thanks a lot, let me check what I can do with this iterators mess

**Comment by w8r** [comment]
So far it's really good, it works (apart from union) and works faster than jsts

**Comment by w8r** [comment]
can you pick up my changes from the branch https://github.com/w8r/martinez/tree/rowanwins-use-avl-tree?

**Comment by w8r** [comment]
but the demo case with 2 polygons with holes is broken (incorrectly constructed multipolygon, rings are fine though)

**Comment by w8r** [comment]
It's been like that before though

**Comment by rowanwins** [comment]
Hey @w8r 

Awesome, glad to hear it sounds like it's getting close again. I must admit I didn't actually look at the visual demo last night, I was just running the tests (somewhat unusual for me!)

I'll take a look at your branch and if I can contribute anything meaningful to the issue re holes and unions.

**Comment by w8r** [comment]
The interactive example is `/demo/` (without #geo hash)
The correctness of the rings can be seen if you would add 
```js
if (op === OPERATIONS.UNION) {
  result.push(result[0][1][0], [result[0][2]]);
  result[0] = [result[0][0]];
}
``` 
after the operation

**Comment by rowanwins** [comment]
Gday @w8r 

So that fix above works on the `/demo/` page but it doesn't work on the `demo/#geo` page. So yeah something going on with union operations and multipolys, some more head scratching required...

Also looking at that `#geo` page the martinez difference is slower than jsts, and the performance gains in martinez for the other operations are much less significant. From what I can tell the `geo` page is using the new avl based script so I wonder why on larger geometries performance seems to decline. Might need to do some digging

**Comment by w8r** [comment]
That's really strange, my measurements yesterday showed up to 2x gain in comparison to jsts on #geo. But i will dig

Kind regards,
Alexander Milevski

**Comment by rowanwins** [comment]
Working being continued in #41

**Pull request closed without merging**
