### PR TITLE
Add ESLint mourner config

### PR DESCRIPTION
**Pull request by DenisCarriere**
Converted library to `eslint-mourner-config`, no linting issues `npm run lint`.

I had to include a few `eslint-disable` which can be found here https://github.com/w8r/martinez/commit/0414bfa92ce48841e683bfa479e122f0dc106bcb.

Ref: #25

### CODE REVIEW

**Comment by w8r** [comment]
I really don't like the removal of vertical alignment, that's a very useful formatting technique, especially with my attention span being similar to that of a fish. Maybe I can create a fork of the eslint standard with this feature added? Though keeping that in the `.eslintrc` is just simpler

**Comment by DenisCarriere** [comment]
We can include the vertical alignment if you prefer that instead, we can add it to the `package.json` (the less files in the repo the better - another personal preference).

**Comment by DenisCarriere** [comment]
You can add custom rules in the [`package.json`](https://github.com/DenisCarriere/martinez/blob/8aa216d6e3b40eb75f242f671185fad132537a44/package.json#L35-L40), I've already added the 2 space indentation. Including an `.eslintrc` was a bit excessive for 3 LOC (the reason why it's bundled in the `package.json`).

```json
"eslintConfig": {
  "extends": "mourner",
  "rules": {
    "indent": [2, 2]
  }
}
```

**Comment by w8r** [comment]
Thanks a lot!

**Pull request merged**
