### PR TITLE
Use original geojson as input

### PR DESCRIPTION
**Pull request by rowanwins**
This resolves the issue identified in #118 by using the original geojson where it's available rather than stuff that's been passed through leaflet.

### CODE REVIEW

**Comment by w8r** [comment]
But leaflet is not supposed to do anything with it, the clipping and path simplification are only done in the rendering and don't affect the initial latLngs

**Comment by rowanwins** [comment]
I does seems strange @w8r but I'm having a hard time pinning things down. 

I just noticed that the codepen used the same behaviour of passing things into leaflet and then back again... so perhaps it's not what I thought... 

Does the #110 set of polygons work for you when you run the demo locally?

**Comment by rowanwins** [comment]
So we could possibly close this - although I think my preference would be to still merge it and use the raw geojson rather than passing it into leaflet and back again, just seems a bit less risky.

**Comment by bluenote10** [comment]
Does that mean there is a different cause of the modified input values we have seen in #111 / [comment](https://github.com/w8r/martinez/pull/111#issuecomment-573391880) or does this PR solve that?

**Comment by rowanwins** [comment]
There are also [some lines](https://github.com/w8r/martinez/blob/master/demo/js/index.js#L157-L158) in the current master demo site which stringify and parse the input data so that could be responsible also...

**Comment by rowanwins** [comment]
It seems like #85 is impacted by the demo site change. Works on the `master` branch, but not on this branch.

**Pull request merged**
