### PR TITLE
Update exports and types

### PR DESCRIPTION
**Pull request by PizzaBrandon**
Adds named exports in addition to the default. This will fix turf and other imports that expect to use `import *` that don't otherwise get picked up correctly since they presently only exist as properties on the exported `boolean` function object.

Type file update to add `export default` was to support `import martinez` functionality as described in the README. I also checked the packages that depend on martinez listed in NPM and verified they all look for ^0.3.x at the highest (except for turf, which I am also fixing) so this shouldn't break any consumer.

### CODE REVIEW

**Comment by PizzaBrandon** [comment]
I realize this PR came as a bit of a surprise after the previous one. Do you have any questions or concerns about this one?

**Comment by PizzaBrandon** [comment]
The `package.json` change was to reflect the fact that the top-level `index.js` is no longer needed. I accidentally took out `index.d.ts`, which *is* still required. (I have updated my PR.) `index.js` only existed to export `boolean` so I opted to have the named exports live directly in `src/index`.

I personally wouldn't be opposed to not having a `default` export. It actually made this change harder to get right.

**Comment by PizzaBrandon** [comment]
I have also verified through a privately-published version of this package and of the affected turf packages that this change allows webpack to correctly build this package into a bundled output.

**Comment by w8r** [comment]
So would you mind removing the default export as well and I will merge

**Comment by PizzaBrandon** [comment]
Do you want me to also update the README documentation?

**Comment by w8r** [comment]
Yes, please!

**Comment by w8r** [comment]
Alternatively, the root `index.js` can be kept and used for API only, then `boolean` can be exported as default from `src/index`

**Comment by w8r** [comment]
that way it would be even cleaner

**Comment by PizzaBrandon** [comment]
PR updated. That change could be made. I had some trouble getting something similar to work, but it was late and I don't remember all what was going wrong.

**Comment by w8r** [comment]
closed in #84

**Pull request closed without merging**
