### PR TITLE
Move to modern code style; StandardJS

### PR DESCRIPTION
**Pull request by z3dev**
These changes move the project to a modern code style called StandardJS (https://standardjs.com/), which is highly regarded as the best. This will help to eliminate any code junkies, and reduce discussions about style.

Also, the ROLLUP versions and plugins were ancient, so those have been bumped to the latest.

There are no logic changes, only style changes to src and test contents.

Test suites run perfectly. Bench runs perfectly, and shows the same performance.

Finally, I suggest getting rid of package-lock.json, and use HARD version numbers for all dependencies. It's a wild west out there.

### CODE REVIEW

**Comment by z3dev** [comment]
@w8r any comments? Is this project still alive?

**Comment by w8r** [comment]
@z3dev Hi there! Thanks a lot for your PR
I will need some time to take a look at it
First off, I am strongly against the standard style (specifically no semicolons), and there's already a linter for it. It doesn't add much value.

**Comment by bluenote10** [comment]
> First off, I am strongly against the standard style (specifically no semicolons)

Me too :).

> which is highly regarded as the best.

Is that so? Isn't `standard` so 2015? As far as I can see from npm download statistics and experience in projects, I'd say that `prettier` has surpassed `standard` by a lot in the last few years:

image

**Comment by z3dev** [comment]
@w8r no problem. You can decide which ever way you want to g with style. I’m just trying to simplify the choice.

as fas as semicolons go… if you can stomach PEP8 then this is an easy transition.

prettier Is fine as well but eslint configuration will still be required.

**Comment by w8r** [comment]
I was thinking of Prettier + typescript

**Comment by bluenote10** [comment]
> I was thinking of Prettier + typescript

> prettier Is fine as well but eslint configuration will still be required.

Indeed, typescript + prettier + eslint (which has replaced tslint, i.e., can handle typescript just fine) is a very popular combo I'd say.

**Comment by z3dev** [comment]
So, just one more question before I close this PR….

why are there approved PRs that haven’t been merged?

**Comment by w8r** [comment]
Are you talking about [this one](https://github.com/w8r/martinez/pull/125) ? I should re-test it and release

**Comment by z3dev** [comment]
Yup. That told me a lot about this project…

**Comment by w8r** [comment]
@z3dev thanks a lot for your support. I am trying to maintain it for free in my spare time, so judgement is definitely appreciated.

**Pull request closed without merging**
