### PR TITLE
Rowanwins output formatting

### PR DESCRIPTION
**Pull request by w8r**
Re-fitting @rowanwins changes

* removed ES5 loops
* removed unnecessary arrays copying

/cc @rowanwins, @DenisCarriere

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@w8r Any reason why the removal of `forEach` ES5 method?
I highly doubt you're attempting to build this library pre-IE 9 (ES5 is supported by Internet Explorer 9).

[https://kangax.github.io/compat-table/es5](https://kangax.github.io/compat-table/es5/#test-Array_methods_Array.prototype.forEach_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;)

ES5 functions make the code very legible and still compatible with 99% of all browsers.

## [Before](https://github.com/w8r/martinez/pull/30/commits/d23ce2845e5e7ae11eac7bd7f774a0ee3a556eb8#diff-1fdf421c05c1140f6d71444ea2b27638L83)

```javascript
clipping.forEach(function (contour) {
  contour.forEach(function (contourOrHole, index) {
```

## [After](https://github.com/w8r/martinez/pull/30/commits/d23ce2845e5e7ae11eac7bd7f774a0ee3a556eb8#diff-1fdf421c05c1140f6d71444ea2b27638R71)
```javascript
for (i = 0, ii = subject.length; i < ii; i++) {
  polygonSet = subject[i];
  for (j = 0, jj = polygonSet.length; j < jj; j++) {
```

If my vote counts on this one, I prefer what @rowanwins wrote in ES5.

**Comment by w8r** [comment]
Agree about the shortness and browser support, don't agree about readability, second one was really difficult to understand, and it was not because of the `.forEach`. So since the performance is usually much better with regular loops (0.8ms vs 5ms for the correction loop) I'd go for the loops. 

@DenisCarriere, @rowanwins  Do you think the ES5 methods would really make a difference in this lib?

**Comment by rowanwins** [comment]
The main reason I converted to the `forEach` was while I was trying to get my head around it, I tend to find them a bit more readable but that's my personal preference. 

I've also heard that `forEach` loops are slower so I'm happy to go with the traditional for loop given that we're aiming for high performance on potentially large arrays.

**Comment by w8r** [comment]
@rowanwins what do you think about the removal of your flags that were stored with the coordinates? I couldn't find any further use of that, that was just debugging, right?

**Comment by DenisCarriere** [comment]
> since the performance is usually much better with regular loops (0.8ms vs 5ms for the correction loop) I'd go for the loops.
If that's the case, then definitely go for loops! 👍 (didn't know it was slowing it down that much)

> Do you think the ES5 methods would really make a difference in this lib?
Same comment as @rowanwins readability is easier, but it's definitely not required.

**Comment by rowanwins** [comment]
@w8r My additional flag does get used in the final stage, around line 480 (sorry not on my computer), there might be a better way to do it but I think it is required...

**Comment by w8r** [comment]
@rowanwins, no, not this one, but [when you put boolean values into the coord arrays](https://github.com/rowanwins/martinez/blob/fdf26b3c2ed1f03ca8f6b67f41988a98d11d90ad/src/index.js#L535) and then filter them out on the next step. I couldn't find any further use and removed it, which also improved memory management in the next loop.

**Comment by rowanwins** [comment]
Honestly I have no recollection, if we can get rid of it without breaking things let's do it!

**Comment by w8r** [comment]
already did)

**Pull request merged**
